"""Aula06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdHJOK62_Kb3TLBE_z6mxTcn5wulFNdY

Execicios 01

Escreva um programa que calcule a porcentagem de comissão de vendedores com as seguintes condições

Venda Total
de R$ 0.00 a R$ 30000.00 - 0%
de R$ 30000.01 a R$ 50000.00 - 1.5%
de R$ 50000.01 a R$ 100000.00 - 2.5%
Acima de R$ 100000.00 - 3.5%
"""


sell = float(input("quanto você vendeu? "))
porcentagem = 0

if (sell > 30000 and sell < 50000):
    porcentagem = 1.5 
elif (sell > 50000 and sell < 100000):
    porcentagem = 2.5
elif (sell > 100000):
    porcentagem = 3.5
comissão = sell/100*porcentagem
print("sua comissão é "+ str(comissão))